/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-01-05 15:52:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class show_jsp extends org.apache.jasper.runtime.HttpJspBase
        implements org.apache.jasper.runtime.JspSourceDependent,
        org.apache.jasper.runtime.JspSourceImports {

    private static final javax.servlet.jsp.JspFactory _jspxFactory =
            javax.servlet.jsp.JspFactory.getDefaultFactory();
    private static final java.util.Set<java.lang.String> _jspx_imports_packages;
    private static final java.util.Set<java.lang.String> _jspx_imports_classes;
    private static java.util.Map<java.lang.String, java.lang.Long> _jspx_dependants;

    static {
        _jspx_imports_packages = new java.util.HashSet<>();
        _jspx_imports_packages.add("javax.servlet");
        _jspx_imports_packages.add("javax.servlet.http");
        _jspx_imports_packages.add("javax.servlet.jsp");
        _jspx_imports_classes = null;
    }

    private volatile javax.el.ExpressionFactory _el_expressionfactory;
    private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

    public java.util.Map<java.lang.String, java.lang.Long> getDependants() {
        return _jspx_dependants;
    }

    public java.util.Set<java.lang.String> getPackageImports() {
        return _jspx_imports_packages;
    }

    public java.util.Set<java.lang.String> getClassImports() {
        return _jspx_imports_classes;
    }

    public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
        if (_el_expressionfactory == null) {
            synchronized (this) {
                if (_el_expressionfactory == null) {
                    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
                }
            }
        }
        return _el_expressionfactory;
    }

    public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
        if (_jsp_instancemanager == null) {
            synchronized (this) {
                if (_jsp_instancemanager == null) {
                    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
                }
            }
        }
        return _jsp_instancemanager;
    }

    public void _jspInit() {
    }

    public void _jspDestroy() {
    }

    public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
            throws java.io.IOException, javax.servlet.ServletException {

        if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
            final java.lang.String _jspx_method = request.getMethod();
            if ("OPTIONS".equals(_jspx_method)) {
                response.setHeader("Allow", "GET, HEAD, POST, OPTIONS");
                return;
            }
            if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
                response.setHeader("Allow", "GET, HEAD, POST, OPTIONS");
                response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
                return;
            }
        }

        final javax.servlet.jsp.PageContext pageContext;
        javax.servlet.http.HttpSession session = null;
        final javax.servlet.ServletContext application;
        final javax.servlet.ServletConfig config;
        javax.servlet.jsp.JspWriter out = null;
        final java.lang.Object page = this;
        javax.servlet.jsp.JspWriter _jspx_out = null;
        javax.servlet.jsp.PageContext _jspx_page_context = null;


        try {
            response.setContentType("text/html; charset=ISO-8859-1");
            pageContext = _jspxFactory.getPageContext(this, request, response,
                    null, true, 8192, true);
            _jspx_page_context = pageContext;
            application = pageContext.getServletContext();
            config = pageContext.getServletConfig();
            session = pageContext.getSession();
            out = pageContext.getOut();
            _jspx_out = out;

            out.write("\r\n");
            out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
            out.write("<html>\r\n");
            out.write("<head>\r\n");
            out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
            out.write("<title>Insert title here</title>\r\n");
            out.write("</head>\r\n");
            out.write("<body>\r\n");
            out.write("	<center>\r\n");
            out.write("		<h1>Java Training Center</h1>\r\n");
            out.write("		<table border=\"2\" style=\"font-size: 26; color: red;\">\r\n");
            out.write("			<tr>\r\n");
            out.write("				<td>1)String,Wrapper and Date :</td>\r\n");
            out.write("				<td><m:out value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.EM}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("\"></m:out><br>\r\n");
            out.write("					");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.PH }", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("<br> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${applicationScope.DOB }", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("<br></td>\r\n");
            out.write("			</tr>\r\n");
            out.write("			<tr>\r\n");
            out.write("				<td>2)Collection of String,Wrapper and Date :</td>\r\n");
            out.write("				<td><table bgcolor=\"#c3d559\" style=\"font-size: 26;\">\r\n");
            out.write("						<tr>\r\n");
            out.write("							<m:forEach var=\"x\"items\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.AL }", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("\">\r\n");
            out.write("								<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x }", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("							</m:forEach>\r\n");
            out.write("						</tr>\r\n");
            out.write("					</table>\r\n");
            out.write("					<table>\r\n");
            out.write("						<tr>\r\n");
            out.write("							<m:forEach var=\"i\" items=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.STR }", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("\">\r\n");
            out.write("								<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("							</m:forEach>\r\n");
            out.write("						</tr>\r\n");
            out.write("					</table></td>\r\n");
            out.write("			</tr>\r\n");
            out.write("			<tr>\r\n");
            out.write("				<td>3) Collection of Collections :</td>\r\n");
            out.write("				<td><table bgcolor=\"#c3d599\" style=\"font-size: 26; color: red;\">\r\n");
            out.write("						<m:forEach var=\"list\" items=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.AL1}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("\">\r\n");
            out.write("							<tr>\r\n");
            out.write("								<m:forEach var=\"x\" items=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("\">\r\n");
            out.write("									<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("								</m:forEach>\r\n");
            out.write("							</tr>\r\n");
            out.write("						</m:forEach>\r\n");
            out.write("					</table></td>\r\n");
            out.write("			</tr>\r\n");
            out.write("			<tr>\r\n");
            out.write("				<td>4) Customer or User Defined Class Object :</td>\r\n");
            out.write("				<td>Cid :");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.CUST.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("<br> Email\r\n");
            out.write("					:");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.CUST.email}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("<br> Phone\r\n");
            out.write("					:");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.CUST.phone }", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("<br> Accno\r\n");
            out.write("					:");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.CUST.account.accno }", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("<br> AType\r\n");
            out.write("					:");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.CUST.account.atype }", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("<br> Bal\r\n");
            out.write("					:");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.CUST.account.bal}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("<br> Street\r\n");
            out.write("					:");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.CUST.account.address.street}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("<br> City\r\n");
            out.write("					:");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.CUST.account.address.city}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("<br></td>\r\n");
            out.write("			</tr>\r\n");
            out.write("\r\n");
            out.write("			<tr>\r\n");
            out.write("				<td>5) Collection or User Defined Class Object</td>\r\n");
            out.write("				<td><table bgcolor=\"#c3d599\" style=\"font-size: 26; color: red;\">\r\n");
            out.write("						<tr>\r\n");
            out.write("							<td>Cid</td>\r\n");
            out.write("							<td>CName</td>\r\n");
            out.write("							<td>Email</td>\r\n");
            out.write("							<td>Phone</td>\r\n");
            out.write("							<td>Accno</td>\r\n");
            out.write("							<td>AType</td>\r\n");
            out.write("							<td>Bal</td>\r\n");
            out.write("							<td>Street</td>\r\n");
            out.write("							<td>City</td>\r\n");
            out.write("						</tr>\r\n");
            out.write("						<m:forEach var=\"cust\" items=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.CS}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("\">\r\n");
            out.write("							<tr>\r\n");
            out.write("								<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cust.cid}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("								<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cust.cname }", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("								<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cust.email }", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("								<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cust.phone }", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("								<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cust.account.accno }", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("								<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cust.account.atype }", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("								<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cust.account.bal }", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("								<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cust.account.address.street }", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("								<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cust.account.address.city }", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("							</tr>\r\n");
            out.write("						</m:forEach>\r\n");
            out.write("					</table></td>\r\n");
            out.write("			</tr>\r\n");
            out.write("\r\n");
            out.write("			<tr>\r\n");
            out.write("				<td>6) Map Object</td>\r\n");
            out.write("				<td><table style=\"font-size: 26; color: red;\">\r\n");
            out.write("						<tr>\r\n");
            out.write("							<td>Map Key</td>\r\n");
            out.write("							<td>Map value</td>\r\n");
            out.write("						</tr>\r\n");
            out.write("						<m:forEach var=\"entry\" items=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.HM}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("\">\r\n");
            out.write("							<tr>\r\n");
            out.write("								<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entry.key}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("								<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entry.value}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("							</tr>\r\n");
            out.write("						</m:forEach>\r\n");
            out.write("					</table></td>\r\n");
            out.write("			</tr>\r\n");
            out.write("\r\n");
            out.write("			<tr>\r\n");
            out.write("				<td>7) Collection of Map Object</td>\r\n");
            out.write("				<td><table bgcolor=\"white\" style=\"font-size: 26; color: red;\">\r\n");
            out.write("						<m:forEach var=\"map\" items=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.AL2}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("\">\r\n");
            out.write("							<tr>\r\n");
            out.write("								<td><table bgcolor=\"#c3d599\"\r\n");
            out.write("										style=\"font-size: 26; color: red\">\r\n");
            out.write("										<tr>\r\n");
            out.write("											<td>Map Key</td>\r\n");
            out.write("											<td>Map value</td>\r\n");
            out.write("										</tr>\r\n");
            out.write("										<m:forEach var=\"entry\" items=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("\">\r\n");
            out.write("											<tr>\r\n");
            out.write("												<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entry.key }", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("												<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entry.value }", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("											</tr>\r\n");
            out.write("										</m:forEach>\r\n");
            out.write("									</table></td>\r\n");
            out.write("							</tr>\r\n");
            out.write("						</m:forEach>\r\n");
            out.write("					</table></td>\r\n");
            out.write("			</tr>\r\n");
            out.write("\r\n");
            out.write("		</table>\r\n");
            out.write("	</center>\r\n");
            out.write("</body>\r\n");
            out.write("</html>");
        } catch (java.lang.Throwable t) {
            if (!(t instanceof javax.servlet.jsp.SkipPageException)) {
                out = _jspx_out;
                if (out != null && out.getBufferSize() != 0)
                    try {
                        if (response.isCommitted()) {
                            out.flush();
                        } else {
                            out.clearBuffer();
                        }
                    } catch (java.io.IOException e) {
                    }
                if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
                else throw new ServletException(t);
            }
        } finally {
            _jspxFactory.releasePageContext(_jspx_page_context);
        }
    }
}
